<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'uuid' => 'b926a7b0-3675-4daf-9e69-4c3d4af5e8c5',
                'collection_name' => 'technical_data_sheets',
                'name' => 'OC Tech',
                'file_name' => '01JGY5G6DF6NAP41NPERV4C43P.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-06 15:59:54',
                'updated_at' => '2025-01-06 15:59:54',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'uuid' => 'ff9c8b2c-032a-4ea9-92fe-acac24d39f56',
                'collection_name' => 'supports',
                'name' => 'OC Tech',
                'file_name' => '01JGY5G6EJ2F90HD8R283RQ3ZH.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 15:59:54',
                'updated_at' => '2025-01-06 15:59:54',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'uuid' => '11d0a132-fc97-4485-a334-bb7fa2f1d496',
                'collection_name' => 'technical_data_sheets',
            'name' => 'Estimacion de costo de proyectos para  Grupo Walworth (2)',
                'file_name' => '01JGY5K4SMQAG7TCKR1EYW75AX.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 68574,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-06 16:01:30',
                'updated_at' => '2025-01-06 16:01:30',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'uuid' => 'd0b04158-6985-4ee6-90a1-02d9378ba5eb',
                'collection_name' => 'supports',
            'name' => 'Estimacion de costo de proyectos para  Grupo Walworth (2)',
                'file_name' => '01JGY5K4TEJTA7ZJSRQATXGS8P.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 68574,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 16:01:30',
                'updated_at' => '2025-01-06 16:01:30',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => 'dbb836f4-dbf9-4321-b700-e2453c5ae36f',
                'collection_name' => 'justification',
                'name' => 'Minuta de reunión SaTech Modulo de configuracion',
                'file_name' => '01JGY5ZM8AQ041EKQ911M2W24Q.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 74082,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-06 16:08:19',
                'updated_at' => '2025-01-06 16:08:19',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '393094e5-eb2b-4e3e-b63e-5a774c4c339a',
                'collection_name' => 'comparative_table',
            'name' => 'Estimacion de costo de proyectos para  Grupo Walworth (2)',
                'file_name' => '01JGY5ZM95ER7BXAG633TBJXVW.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 68574,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 16:08:20',
                'updated_at' => '2025-01-06 16:08:20',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '9a6fd5e0-2292-4141-b672-07c7c6380915',
                'collection_name' => 'certifications',
                'name' => 'platilla propuesta de software ingles',
                'file_name' => '01JGY5ZM9R3JJJ9TP8BV0ARZ85.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 56387,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-01-06 16:08:20',
                'updated_at' => '2025-01-06 16:08:20',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'dcfdfd7e-665d-46c0-bbbe-61d83144a089',
                'collection_name' => 'justification',
                'name' => 'Tabla Soldadoras 2',
                'file_name' => '01JGY6CCNHTM6TS4H93NCE9FEG.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 196361,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'e1351a44-7979-4884-a022-f3f25830418a',
                'collection_name' => 'comparative_table',
                'name' => 'Minuta de reunión SaTech Modulo de configuracion',
                'file_name' => '01JGY6CCPB726CFFPXC4A56FXR.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 74082,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => '9fb2df75-98e9-4313-9bcf-248791afdcec',
                'collection_name' => 'certifications',
                'name' => 'Prueba de impresion',
                'file_name' => '01JGY6CCPW18ZQ4FGQBS1YA6R1.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 182871,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
        ));
        
        
    }
}