<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'e1351a44-7979-4884-a022-f3f25830418a',
                'collection_name' => 'comparative_table',
                'name' => 'Minuta de reunión SaTech Modulo de configuracion',
                'file_name' => '01JGY6CCPB726CFFPXC4A56FXR.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 74082,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
            1 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '0db881df-5748-42df-9a7f-20789e337a9d',
                'collection_name' => 'comparative_table',
                'name' => 'OC Tech',
                'file_name' => '01JH63AN2AZHPKEE1125T8Q4FV.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2025-01-09 17:55:51',
                'updated_at' => '2025-01-09 17:55:51',
            ),
            2 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '31803fae-17f1-491a-98e1-6eba7190a052',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ4XYY2Z0RZCZMBAA76AE6JY.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            3 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '49119e27-7123-48bc-a452-29e7d377dc09',
                'collection_name' => 'direct_award',
            'name' => 'Infografias y comunicados (2)',
                'file_name' => '01JJ4XYY4H7KNH4259R3Y04JQ9.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 54647,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            4 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => 'b2c5b581-a462-4d6d-9c3f-1bb958358424',
                'collection_name' => 'certifications',
                'name' => 'generate_tickets',
                'file_name' => '01JJ4XYY5PYS3GGTD7RTF7EZGD.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 320972,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            5 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => 'dbaa722c-31f8-4bc1-82f1-0fd9e0f9ca98',
                'collection_name' => 'quote',
                'name' => 'recibo_cfe',
                'file_name' => '01JJ4XYY6JA8HH88777KFRT042.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 119798,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            6 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => '258b2be6-17fa-463d-a327-4157ea894b10',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ78NB6GCYT9VHKWJ49BKEK6.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2025-01-22 15:04:00',
                'updated_at' => '2025-01-22 15:04:00',
            ),
            7 => 
            array (
                'id' => 33,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'dbda0f46-f75e-428b-bc1b-c2cb57f7b3b0',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JJ78NB7TRNTCYVRBNRE7V4DX.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2025-01-22 15:04:00',
                'updated_at' => '2025-01-22 15:04:00',
            ),
            8 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => '8c4a60f1-0695-41c9-b6b1-7808fdedffef',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JJ78NB8N9176ZEEYKP9JMN4B.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2025-01-22 15:04:00',
                'updated_at' => '2025-01-22 15:04:00',
            ),
            9 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'a941a396-5943-4de3-a36b-56349684d348',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JJ78NB9P11XVCJQKDQYWE9JJ.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 11,
                'created_at' => '2025-01-22 15:04:00',
                'updated_at' => '2025-01-22 15:04:00',
            ),
            10 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '0ed1cadf-9a5b-4894-a16b-ddfd40b6bfe0',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ7J4X1VZ6H68T6G5ZTVTTW3.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2025-01-22 17:49:47',
                'updated_at' => '2025-01-22 17:49:47',
            ),
            11 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '50c9bf84-011a-4d68-978a-b6427055e157',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JJ7J4X3D5VNWS17MBSFZR79Z.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2025-01-22 17:49:47',
                'updated_at' => '2025-01-22 17:49:47',
            ),
            12 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => 'ce1e2dc4-e4b0-4d27-9f40-eb6156841f5a',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JJ7J4X4DSN8VBK823F4MXTXV.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2025-01-22 17:49:47',
                'updated_at' => '2025-01-22 17:49:47',
            ),
            13 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '26c5c98a-5893-4683-9418-178aed9c9502',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JJ7J4X5C0X53SKAVXWBY2ZJ1.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2025-01-22 17:49:47',
                'updated_at' => '2025-01-22 17:49:47',
            ),
            14 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '50f56959-737c-4a4d-91b9-312af7f0d777',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JC4H7N0MX0MQWR75NKRZ2.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2025-01-22 17:53:44',
                'updated_at' => '2025-01-22 17:53:44',
            ),
            15 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '769adcb0-3c96-4f14-9d54-0b7c12fffbca',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JC4JQ8T16Q4HDHRB4T00A.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2025-01-22 17:53:44',
                'updated_at' => '2025-01-22 17:53:44',
            ),
            16 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '44b80c47-f156-41aa-b45f-45a59d66823d',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JC4KPF5H271CJJ4PFEH9Y.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2025-01-22 17:53:44',
                'updated_at' => '2025-01-22 17:53:44',
            ),
            17 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => 'a739ae50-ee74-4e6a-80ca-f9f801c7db29',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JC4MPW61ZTJ5BV2SZHAQP.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2025-01-22 17:53:44',
                'updated_at' => '2025-01-22 17:53:44',
            ),
            18 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'uuid' => 'd0b64177-734a-44ea-ba40-3c67b4fbf6e6',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JEEEAANW12JB9GH0RDKY6.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-22 17:55:00',
                'updated_at' => '2025-01-22 17:55:00',
            ),
            19 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'uuid' => '2b7f9989-c92f-49f2-a536-d5b12c7ab843',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JEEFGFBJ0C7DKK1DA1QZD.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-22 17:55:00',
                'updated_at' => '2025-01-22 17:55:00',
            ),
            20 => 
            array (
                'id' => 46,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'uuid' => 'b5c4f357-c47f-4c24-9dfa-711b9c1f1386',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JEEGDHXZ6QFCTV7CDVM7H.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-01-22 17:55:00',
                'updated_at' => '2025-01-22 17:55:00',
            ),
            21 => 
            array (
                'id' => 47,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'uuid' => '1465fb35-0c4d-4ee9-90ff-07b60263cc58',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JJ7JEEHBV2ABX3FY721D4JBA.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2025-01-22 17:55:00',
                'updated_at' => '2025-01-22 17:55:00',
            ),
            22 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'uuid' => 'a4399a5b-9aac-4d23-a1fd-e189250410a4',
                'collection_name' => 'technical_data_sheets',
                'name' => 'OC Tech',
                'file_name' => '01JJ8DJZZH085622A5VZWFR9WC.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-23 01:49:20',
                'updated_at' => '2025-01-23 01:49:20',
            ),
            23 => 
            array (
                'id' => 49,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'uuid' => 'b9abe271-96a2-4c28-84cb-20e57fb8c678',
                'collection_name' => 'supports',
                'name' => 'OC Tech',
                'file_name' => '01JJ8DK01R9N57WX2BFN0NPNNA.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-23 01:49:20',
                'updated_at' => '2025-01-23 01:49:20',
            ),
        ));
        
        
    }
}