<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MediaTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('media')->delete();
        
        \DB::table('media')->insert(array (
            0 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'e1351a44-7979-4884-a022-f3f25830418a',
                'collection_name' => 'comparative_table',
                'name' => 'Minuta de reunión SaTech Modulo de configuracion',
                'file_name' => '01JGY6CCPB726CFFPXC4A56FXR.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 74082,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
            1 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '0db881df-5748-42df-9a7f-20789e337a9d',
                'collection_name' => 'comparative_table',
                'name' => 'OC Tech',
                'file_name' => '01JH63AN2AZHPKEE1125T8Q4FV.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2025-01-09 17:55:51',
                'updated_at' => '2025-01-09 17:55:51',
            ),
            2 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'c1ff3e74-c599-442c-baec-77d62b37e802',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JHG4T1DHKJX4SHWF2W0TX2HW.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2025-01-13 15:34:08',
                'updated_at' => '2025-01-13 15:34:08',
            ),
            3 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => 'c32914bd-aa32-491b-827f-3bf9e29bcefa',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JHG4T1F9Q7EKPWT93X687SN7.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 5,
                'created_at' => '2025-01-13 15:34:08',
                'updated_at' => '2025-01-13 15:34:08',
            ),
            4 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => '38ece39e-93d3-409c-93f7-3034bb478805',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JHG4T1GB07AZFAKBKSQSAC0R.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 6,
                'created_at' => '2025-01-13 15:34:08',
                'updated_at' => '2025-01-13 15:34:08',
            ),
            5 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'uuid' => '6c9fc318-247e-460b-a654-c3c94595ba5e',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JHG4T1H4M9E2W55BQ2PXGF8H.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2025-01-13 15:34:08',
                'updated_at' => '2025-01-13 15:34:08',
            ),
            6 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '6fc32c42-bf0d-410a-bf81-df0668ecca19',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JHN9RK83G6MYE2SV1RM2ZH1N.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-15 15:36:55',
                'updated_at' => '2025-01-15 15:36:55',
            ),
            7 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '2bbccf94-2032-44ce-9ce8-19f57eb819f3',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JHN9RKA4ZTT6RZM39H2BHEAV.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-15 15:36:55',
                'updated_at' => '2025-01-15 15:36:55',
            ),
            8 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => 'ca4c3de3-3b53-43db-9660-5ab7e9fa3dcf',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JHN9RKB0SM0TZ3N57NJJ5HNR.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-01-15 15:36:55',
                'updated_at' => '2025-01-15 15:36:55',
            ),
            9 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'uuid' => '6c462115-b08a-43b7-a0d1-c266a2789e8f',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JHN9RKBSV84HN37SNK3R4APW.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2025-01-15 15:36:55',
                'updated_at' => '2025-01-15 15:36:55',
            ),
            10 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '71804fbc-3dc4-4c65-8d11-ec05f9f37e00',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JHTXTNKF0HYAT8SBVBB6TG4Y.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 1,
                'created_at' => '2025-01-17 20:03:47',
                'updated_at' => '2025-01-17 20:03:47',
            ),
            11 => 
            array (
                'id' => 25,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '13abafa7-a60c-4344-bd98-5d0b47b1d028',
                'collection_name' => 'direct_award',
                'name' => 'OC Tech',
                'file_name' => '01JHTXTNNV783WXP55P2CVD53E.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 2,
                'created_at' => '2025-01-17 20:03:47',
                'updated_at' => '2025-01-17 20:03:47',
            ),
            12 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => 'b37e5c69-61d0-42fd-94d5-fbf348433389',
                'collection_name' => 'certifications',
                'name' => 'OC Tech',
                'file_name' => '01JHTXTNPZZJZMV0YNRT4KF11V.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 3,
                'created_at' => '2025-01-17 20:03:47',
                'updated_at' => '2025-01-17 20:03:47',
            ),
            13 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'uuid' => '7bba3dff-b588-40ae-92e8-b4e35f0530c9',
                'collection_name' => 'quote',
                'name' => 'OC Tech',
                'file_name' => '01JHTXTNR013C023Z4Q40T2EF3.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 4,
                'created_at' => '2025-01-17 20:03:47',
                'updated_at' => '2025-01-17 20:03:47',
            ),
            14 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '31803fae-17f1-491a-98e1-6eba7190a052',
                'collection_name' => 'justification',
                'name' => 'OC Tech',
                'file_name' => '01JJ4XYY2Z0RZCZMBAA76AE6JY.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 740032,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 7,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            15 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => '49119e27-7123-48bc-a452-29e7d377dc09',
                'collection_name' => 'direct_award',
            'name' => 'Infografias y comunicados (2)',
                'file_name' => '01JJ4XYY4H7KNH4259R3Y04JQ9.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 54647,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 8,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            16 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => 'b2c5b581-a462-4d6d-9c3f-1bb958358424',
                'collection_name' => 'certifications',
                'name' => 'generate_tickets',
                'file_name' => '01JJ4XYY5PYS3GGTD7RTF7EZGD.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 320972,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 9,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            17 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'uuid' => 'dbaa722c-31f8-4bc1-82f1-0fd9e0f9ca98',
                'collection_name' => 'quote',
                'name' => 'recibo_cfe',
                'file_name' => '01JJ4XYY6JA8HH88777KFRT042.pdf',
                'mime_type' => 'application/pdf',
                'disk' => 'public',
                'conversions_disk' => 'public',
                'size' => 119798,
                'manipulations' => '[]',
                'custom_properties' => '[]',
                'generated_conversions' => '[]',
                'responsive_images' => '[]',
                'order_column' => 10,
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
        ));
        
        
    }
}