<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StateHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('state_histories')->delete();
        
        \DB::table('state_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-SC-2025-0001", "old": null}, "motive": {"new": "Autem consectetur in vitae consequatur qui dolorem", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-06 15:59:54", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2025-01-06 15:59:54", "old": null}, "observation": {"new": "Quis voluptatum quo aliquid nisi quos dolor est voluptatum ab", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-07 00:00:00", "old": null}, "delivery_address": {"new": "Fugiat eos quis sit iusto sit odit ut", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-06 15:59:54',
                'updated_at' => '2025-01-06 15:59:54',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-06 16:00:57',
                'updated_at' => '2025-01-06 16:00:57',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "G-SC-2025-0002", "old": null}, "motive": {"new": "Amet sint et laborum Tempor consectetur iure ut error et impedit excepturi explicabo Fuga Veniam ipsa eaque aliqua Rem", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-06 16:01:30", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2025-01-06 16:01:30", "old": null}, "observation": {"new": "Perspiciatis dolor neque veniam est fuga Exercitation nihil reiciendis fuga Vel dolor", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-07 00:00:00", "old": null}, "delivery_address": {"new": "Sint eum labore ut ad recusandae Id aliquid lorem laborum cupidatat nulla neque nisi incidunt laborum", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-06 16:01:30',
                'updated_at' => '2025-01-06 16:01:30',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-06 16:01:52',
                'updated_at' => '2025-01-06 16:01:52',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-06 16:02:05',
                'updated_at' => '2025-01-06 16:02:05',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-06 16:02:11',
                'updated_at' => '2025-01-06 16:02:11',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-06 16:02:29',
                'updated_at' => '2025-01-06 16:02:29',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-06 16:02:36',
                'updated_at' => '2025-01-06 16:02:36',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-06 16:02:58',
                'updated_at' => '2025-01-06 16:02:58',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-06 16:03:06',
                'updated_at' => '2025-01-06 16:03:06',
            ),
            10 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-06 16:03:20',
                'updated_at' => '2025-01-06 16:03:20',
            ),
            11 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-06 16:03:26',
                'updated_at' => '2025-01-06 16:03:26',
            ),
            12 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-06 16:05:42',
                'updated_at' => '2025-01-06 16:05:42',
            ),
            13 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-06 16:05:54',
                'updated_at' => '2025-01-06 16:05:54',
            ),
            14 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "8", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "102-Mobiliario y equipo de oficina por inversiones", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-06 16:08:19", "old": null}, "updated_at": {"new": "2025-01-06 16:08:19", "old": null}, "provider_id": {"new": "3", "old": null}, "quote_folio": {"new": "Ut voluptas et odit ", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "Voluptatum tenetur o", "old": null}, "term_payment": {"new": "15 días", "old": null}, "type_payment": {"new": "PPD - Pago en parcialidades o diferido", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "2", "old": null}, "shipping_method": {"new": "Nostrum consequatur ", "old": null}, "condition_payment": {"new": "Eos dolore in enim ", "old": null}, "purchaser_user_id": {"new": 199, "old": null}, "retention_another": {"new": 0, "old": null}, "final_delivery_date": {"new": "2025-01-08", "old": null}, "initial_delivery_date": {"new": "2025-01-07", "old": null}}',
                'created_at' => '2025-01-06 16:08:19',
                'updated_at' => '2025-01-06 16:08:19',
            ),
            15 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-06 16:10:17',
                'updated_at' => '2025-01-06 16:10:17',
            ),
            16 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-06 16:11:10',
                'updated_at' => '2025-01-06 16:11:10',
            ),
            17 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "8", "old": null}, "currency": {"new": "USD", "old": null}, "discount": {"new": "10000", "old": null}, "use_cfdi": {"new": "106-Comunicaciones telefónicas", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-06 16:15:18", "old": null}, "updated_at": {"new": "2025-01-06 16:15:18", "old": null}, "provider_id": {"new": "3", "old": null}, "quote_folio": {"new": "Nobis cupidatat dolo", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "Assumenda eveniet v", "old": null}, "term_payment": {"new": "15 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": "9", "old": null}, "retention_iva": {"new": "9", "old": null}, "requisition_id": {"new": "1", "old": null}, "shipping_method": {"new": "Sed minim dolores si", "old": null}, "condition_payment": {"new": "Quo ducimus qui est", "old": null}, "purchaser_user_id": {"new": 199, "old": null}, "retention_another": {"new": 0, "old": null}, "final_delivery_date": {"new": "2025-01-29", "old": null}, "initial_delivery_date": {"new": "2025-01-14", "old": null}}',
                'created_at' => '2025-01-06 16:15:18',
                'updated_at' => '2025-01-06 16:15:18',
            ),
            18 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-06 16:15:58',
                'updated_at' => '2025-01-06 16:15:58',
            ),
            19 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-06 16:16:52',
                'updated_at' => '2025-01-06 16:16:52',
            ),
            20 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-06 17:16:35',
                'updated_at' => '2025-01-06 17:16:35',
            ),
            21 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-06 17:16:42',
                'updated_at' => '2025-01-06 17:16:42',
            ),
            22 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente solicitante',
                'to' => 'aprobado por DG nivel 1',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG nivel 1", "old": "aprobado por gerente solicitante"}}',
                'created_at' => '2025-01-06 17:19:42',
                'updated_at' => '2025-01-06 17:19:42',
            ),
            23 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerente solicitante',
                'to' => 'aprobada para emisión',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobada para emisión", "old": "aprobado por gerente solicitante"}}',
                'created_at' => '2025-01-06 17:53:09',
                'updated_at' => '2025-01-06 17:53:09',
            ),
            24 => 
            array (
                'id' => 25,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-SG-2025-0001", "old": null}, "motive": {"new": "Iure reiciendis neque sint fugiat a aliquid", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-09 17:31:31", "old": null}, "project_id": {"new": "2", "old": null}, "updated_at": {"new": "2025-01-09 17:31:31", "old": null}, "observation": {"new": "Sapiente suscipit velit perspiciatis nihil qui deserunt perspiciatis tenetur quibusdam quia ea velit qui expedita qui consequatur esse ipsum qui", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-10 00:00:00", "old": null}, "delivery_address": {"new": "Maiores non est magni quisquam possimus eligendi omnis quia velit impedit voluptatibus ut pariatur Et laboris", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-09 17:31:31',
                'updated_at' => '2025-01-09 17:31:31',
            ),
            25 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-09 17:41:36',
                'updated_at' => '2025-01-09 17:41:36',
            ),
            26 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-09 17:42:04',
                'updated_at' => '2025-01-09 17:42:04',
            ),
            27 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-09 17:42:21',
                'updated_at' => '2025-01-09 17:42:21',
            ),
            28 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-09 17:42:45',
                'updated_at' => '2025-01-09 17:42:45',
            ),
            29 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-09 17:43:07',
                'updated_at' => '2025-01-09 17:43:07',
            ),
            30 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-09 17:44:53',
                'updated_at' => '2025-01-09 17:44:53',
            ),
            31 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "8", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "10000", "old": null}, "use_cfdi": {"new": "105-Dados, troqueles, moldes, matrices y herramental", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-09 17:55:50", "old": null}, "updated_at": {"new": "2025-01-09 17:55:50", "old": null}, "provider_id": {"new": "297", "old": null}, "quote_folio": {"new": "Illo et porro ducimu", "old": null}, "form_payment": {"new": "efectivo", "old": null}, "observations": {"new": "Harum anim non sint", "old": null}, "term_payment": {"new": "contado", "old": null}, "type_payment": {"new": "PPD - Pago en parcialidades o diferido", "old": null}, "retention_isr": {"new": "5", "old": null}, "retention_iva": {"new": "5", "old": null}, "requisition_id": {"new": "1", "old": null}, "shipping_method": {"new": "Nostrud error pariat", "old": null}, "condition_payment": {"new": "Rerum magna voluptas", "old": null}, "purchaser_user_id": {"new": 199, "old": null}, "retention_another": {"new": 0, "old": null}, "final_delivery_date": {"new": "2025-01-10", "old": null}, "initial_delivery_date": {"new": "2025-01-10", "old": null}}',
                'created_at' => '2025-01-09 17:55:50',
                'updated_at' => '2025-01-09 17:55:50',
            ),
            32 => 
            array (
                'id' => 33,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-09 17:59:30',
                'updated_at' => '2025-01-09 17:59:30',
            ),
            33 => 
            array (
                'id' => 34,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-09 18:03:55',
                'updated_at' => '2025-01-09 18:03:55',
            ),
            34 => 
            array (
                'id' => 35,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-09 18:04:57',
                'updated_at' => '2025-01-09 18:04:57',
            ),
            35 => 
            array (
                'id' => 36,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "G-SG-2025-0001", "old": null}, "motive": {"new": "Aliqua Vero voluptas mollit id incididunt et sunt aliquip veniam neque omnis do in consequuntur modi aute quas", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-13 15:07:58", "old": null}, "project_id": {"new": "2", "old": null}, "updated_at": {"new": "2025-01-13 15:07:58", "old": null}, "observation": {"new": "Nihil cillum velit et laboris laboriosam mollit sed", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-14 00:00:00", "old": null}, "delivery_address": {"new": "Ex aliqua Enim ducimus enim quidem suscipit labore iusto voluptas labore atque qui eligendi sed lorem est Nam", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-13 15:07:58',
                'updated_at' => '2025-01-13 15:07:58',
            ),
            36 => 
            array (
                'id' => 37,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-13 15:08:28',
                'updated_at' => '2025-01-13 15:08:28',
            ),
            37 => 
            array (
                'id' => 38,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-13 15:08:53',
                'updated_at' => '2025-01-13 15:08:53',
            ),
            38 => 
            array (
                'id' => 39,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-13 15:09:03',
                'updated_at' => '2025-01-13 15:09:03',
            ),
            39 => 
            array (
                'id' => 40,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-13 15:09:46',
                'updated_at' => '2025-01-13 15:09:46',
            ),
            40 => 
            array (
                'id' => 41,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-13 15:10:03',
                'updated_at' => '2025-01-13 15:10:03',
            ),
            41 => 
            array (
                'id' => 42,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-13 15:10:34',
                'updated_at' => '2025-01-13 15:10:34',
            ),
            42 => 
            array (
                'id' => 43,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "0", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "G02-Devoluciones y descuentos sobre compras", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-13 15:34:08", "old": null}, "updated_at": {"new": "2025-01-13 15:34:08", "old": null}, "provider_id": {"new": "295", "old": null}, "quote_folio": {"new": "Distinctio At illum", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": ".", "old": null}, "term_payment": {"new": "15 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "2", "old": null}, "shipping_method": {"new": "Nostrud fuga Vel no", "old": null}, "condition_payment": {"new": "Deserunt non dolorem", "old": null}, "purchaser_user_id": {"new": 199, "old": null}, "retention_another": {"new": 0, "old": null}, "final_delivery_date": {"new": "2025-01-16", "old": null}, "initial_delivery_date": {"new": "2025-01-14", "old": null}}',
                'created_at' => '2025-01-13 15:34:08',
                'updated_at' => '2025-01-13 15:34:08',
            ),
            43 => 
            array (
                'id' => 44,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-14 13:23:24',
                'updated_at' => '2025-01-14 13:23:24',
            ),
            44 => 
            array (
                'id' => 45,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-14 13:23:39',
                'updated_at' => '2025-01-14 13:23:39',
            ),
            45 => 
            array (
                'id' => 46,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-14 13:24:21',
                'updated_at' => '2025-01-14 13:24:21',
            ),
            46 => 
            array (
                'id' => 47,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente solicitante',
                'to' => 'aprobada para emisión',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobada para emisión", "old": "aprobado por gerente solicitante"}}',
                'created_at' => '2025-01-14 13:40:06',
                'updated_at' => '2025-01-14 13:40:06',
            ),
            47 => 
            array (
                'id' => 48,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 3, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "16", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "G03-Gastos en general", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-15 15:36:55", "old": null}, "updated_at": {"new": "2025-01-15 15:36:55", "old": null}, "provider_id": {"new": "343", "old": null}, "quote_folio": {"new": "Ea dolore qui anim s", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "Pariatur Nesciunt ", "old": null}, "term_payment": {"new": "60 días", "old": null}, "type_payment": {"new": "PPD - Pago en parcialidades o diferido", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "2", "old": null}, "shipping_method": {"new": "Excepteur soluta omn", "old": null}, "condition_payment": {"new": "Eu quis occaecat est", "old": null}, "purchaser_user_id": {"new": 199, "old": null}, "final_delivery_date": {"new": "2025-01-17", "old": null}, "provider_contact_id": {"new": "433", "old": null}, "initial_delivery_date": {"new": "2025-01-16", "old": null}}',
                'created_at' => '2025-01-15 15:36:55',
                'updated_at' => '2025-01-15 15:36:55',
            ),
        ));
        
        
    }
}