<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StateHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('state_histories')->delete();
        
        \DB::table('state_histories')->insert(array (
            0 => 
            array (
                'id' => 1,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-VEN-2024-0001", "old": null}, "motive": {"new": "Fugiat libero consectetur pariatur Odit nesciunt sunt occaecat totam officia corrupti aut voluptatem Laboriosam vel dolorem cupiditate", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-11 19:26:55", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-11 19:26:55", "old": null}, "observation": {"new": "Rerum omnis quis est quis magnam cumque illo amet ut quo laborum officia", "old": null}, "date_delivery": {"new": "2024-11-20 00:00:00", "old": null}, "delivery_address": {"new": "Reprehenderit consequuntur adipisci sed sequi facilis", "old": null}, "approval_chain_id": {"new": 1, "old": null}}',
                'created_at' => '2024-11-11 19:26:55',
                'updated_at' => '2024-11-11 19:26:55',
            ),
            1 => 
            array (
                'id' => 2,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2024-11-11 19:32:46',
                'updated_at' => '2024-11-11 19:32:46',
            ),
            2 => 
            array (
                'id' => 3,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": "Quia numquam molesti"}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2024-11-12 15:09:55',
                'updated_at' => '2024-11-12 15:09:55',
            ),
            3 => 
            array (
                'id' => 4,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "G-VEN-2024-0002", "old": null}, "motive": {"new": "Ad veniam necessitatibus voluptas totam voluptatem magna consequatur deserunt perspiciatis ab voluptate est deleniti quasi molestiae accusantium", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-12 15:13:26", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-12 15:13:26", "old": null}, "observation": {"new": "Aspernatur minima ducimus esse nisi aliqua Non", "old": null}, "date_delivery": {"new": "2024-11-13 00:00:00", "old": null}, "delivery_address": {"new": "Et qui voluptatem Qui iste nulla minim veritatis do qui similique at est non", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2024-11-12 15:13:26',
                'updated_at' => '2024-11-12 15:13:26',
            ),
            4 => 
            array (
                'id' => 5,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2024-11-12 15:15:13',
                'updated_at' => '2024-11-12 15:15:13',
            ),
            5 => 
            array (
                'id' => 6,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-ALM-2024-0001", "old": null}, "motive": {"new": "Consequatur aliqua Temporibus harum deserunt qui quam provident fugiat repudiandae provident voluptates commodi iusto", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-13 14:43:07", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-13 14:43:07", "old": null}, "observation": {"new": "Corporis amet eiusmod nostrum delectus ut", "old": null}, "confidential": {"new": true, "old": null}, "date_delivery": {"new": "2024-11-15 00:00:00", "old": null}, "delivery_address": {"new": "Expedita nostrum dolorem et ut quaerat ea impedit odit tempor ea a molestiae non ipsum aut eum", "old": null}}',
                'created_at' => '2024-11-13 14:43:07',
                'updated_at' => '2024-11-13 14:43:07',
            ),
            6 => 
            array (
                'id' => 7,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "G-ALM-2024-0001", "old": null}, "motive": {"new": "Mollit minim exercitation et nihil excepturi cupidatat est aut", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-13 14:43:43", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-13 14:43:43", "old": null}, "observation": {"new": "Repudiandae rerum earum illo voluptatem quisquam enim inventore hic excepteur eius magni voluptatem sequi", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2024-11-28 00:00:00", "old": null}, "delivery_address": {"new": "Sit quaerat eos obcaecati inventore quae labore eiusmod aut iste", "old": null}, "approval_chain_id": {"new": 1, "old": null}}',
                'created_at' => '2024-11-13 14:43:43',
                'updated_at' => '2024-11-13 14:43:43',
            ),
            7 => 
            array (
                'id' => 8,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 3, "old": null}, "folio": {"new": "G-ALM-2024-0002", "old": null}, "motive": {"new": "Cillum quia error sit in", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-13 14:48:20", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-13 14:48:20", "old": null}, "observation": {"new": "Omnis consequatur soluta eos aut", "old": null}, "confidential": {"new": true, "old": null}, "date_delivery": {"new": "2024-11-15 00:00:00", "old": null}, "delivery_address": {"new": "Commodo consectetur corrupti sed ut cillum rerum proident voluptate et qui sit iure perferendis sint ullam dolore eos pariatur", "old": null}, "approval_chain_id": {"new": 1, "old": null}}',
                'created_at' => '2024-11-13 14:48:20',
                'updated_at' => '2024-11-13 14:48:20',
            ),
            8 => 
            array (
                'id' => 9,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'aprobado por revisor',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "borrador"}}',
                'created_at' => '2024-11-13 15:31:13',
                'updated_at' => '2024-11-13 15:31:13',
            ),
            9 => 
            array (
                'id' => 10,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2024-11-13 16:16:54',
                'updated_at' => '2024-11-13 16:16:54',
            ),
            10 => 
            array (
                'id' => 11,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2024-11-13 17:03:49',
                'updated_at' => '2024-11-13 17:03:49',
            ),
            11 => 
            array (
                'id' => 12,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2024-11-13 17:05:17',
                'updated_at' => '2024-11-13 17:05:17',
            ),
            12 => 
            array (
                'id' => 13,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2024-11-13 17:05:52',
                'updated_at' => '2024-11-13 17:05:52',
            ),
            13 => 
            array (
                'id' => 14,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2024-11-13 17:06:07',
                'updated_at' => '2024-11-13 17:06:07',
            ),
            14 => 
            array (
                'id' => 15,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-ALM-2024-0001", "old": null}, "motive": {"new": "Non aut tempora et ut in iure voluptas debitis hic ut facilis molestiae nulla", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-11-14 16:31:09", "old": null}, "project_id": {"new": "1", "old": null}, "updated_at": {"new": "2024-11-14 16:31:09", "old": null}, "observation": {"new": "Aliquid sapiente iusto iusto praesentium ut in ut quia sed vel voluptates sunt voluptas", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2024-11-15 00:00:00", "old": null}, "delivery_address": {"new": "Quis suscipit molestiae officia natus dolore tempor soluta nulla aspernatur omnis", "old": null}, "approval_chain_id": {"new": 1, "old": null}}',
                'created_at' => '2024-11-14 16:31:09',
                'updated_at' => '2024-11-14 16:31:09',
            ),
            15 => 
            array (
                'id' => 16,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2024-11-14 16:34:35',
                'updated_at' => '2024-11-14 16:34:35',
            ),
            16 => 
            array (
                'id' => 17,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": "Voluptate a consequa"}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 250,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2024-11-14 16:35:19',
                'updated_at' => '2024-11-14 16:35:19',
            ),
            17 => 
            array (
                'id' => 18,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 152,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2024-11-14 16:35:50',
                'updated_at' => '2024-11-14 16:35:50',
            ),
            18 => 
            array (
                'id' => 19,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2024-11-14 16:36:12',
                'updated_at' => '2024-11-14 16:36:12',
            ),
            19 => 
            array (
                'id' => 20,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2024-11-14 16:36:33',
                'updated_at' => '2024-11-14 16:36:33',
            ),
            20 => 
            array (
                'id' => 21,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2024-11-21 17:09:20',
                'updated_at' => '2024-11-21 17:09:20',
            ),
            21 => 
            array (
                'id' => 22,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'revisión',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"cp": {"new": "Eu quod qu", "old": null}, "id": {"new": 1, "old": null}, "rfc": {"new": "1234456", "old": null}, "state": {"new": "Esse amet ut minus delectus a voluptate dolore harum placeat adipisci veniam voluptatem iusto delectus rerum saepe iure eu", "old": null}, "number": {"new": "24", "old": null}, "status": {"new": "revisión", "old": null}, "street": {"new": "Aliquid qui quas veritatis in eligendi sed similique necessitatibus in voluptas facilis in harum accusamus dolores rerum accusantium iste laudantium", "old": null}, "country": {"new": "Nam cupidatat ex esse esse soluta numquam dolores aliquip dolore aliquip qui non voluptate", "old": null}, "created_at": {"new": "2024-12-03 16:29:40", "old": null}, "updated_at": {"new": "2024-12-03 16:29:40", "old": null}, "web_company": {"new": "Waller Talley Inc", "old": null}, "company_name": {"new": "proveedor 1", "old": null}, "municipality": {"new": "Consectetur aliquip porro occaecat et nostrum ex", "old": null}, "neighborhood": {"new": "Ut rem maxime in nisi dolore inventore est ut enim consequat Magni quia", "old": null}, "user_request_id": {"new": 199, "old": null}}',
                'created_at' => '2024-12-03 16:29:40',
                'updated_at' => '2024-12-03 16:29:40',
            ),
            22 => 
            array (
                'id' => 23,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'revisión',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 52,
                'changed_attributes' => '{"cp": {"new": "Quae asper", "old": null}, "id": {"new": 2, "old": null}, "rfc": {"new": "3545465", "old": null}, "state": {"new": "Quaerat nihil itaque pariatur Cupiditate voluptas quibusdam consectetur nostrum iure quis sint voluptas eiusmod inventore proident in", "old": null}, "number": {"new": "860", "old": null}, "status": {"new": "revisión", "old": null}, "street": {"new": "Excepturi exercitation quis quibusdam libero eligendi eum praesentium id in tempor vero qui est vitae nisi optio adipisicing et", "old": null}, "country": {"new": "Velit et aliquam magnam placeat optio fugiat dolorem accusantium", "old": null}, "created_at": {"new": "2024-12-03 17:11:27", "old": null}, "updated_at": {"new": "2024-12-03 17:11:27", "old": null}, "web_company": {"new": "Knight Baldwin LLC", "old": null}, "company_name": {"new": "proveedor 2", "old": null}, "municipality": {"new": "Quis dolores cillum error tempore placeat sed voluptate qui quia deserunt quis ex corporis quae ducimus aut", "old": null}, "neighborhood": {"new": "Magni omnis quis aut sed qui neque aut sint quas adipisci optio atque laudantium alias ut aut reprehenderit", "old": null}, "user_request_id": {"new": 52, "old": null}}',
                'created_at' => '2024-12-03 17:11:27',
                'updated_at' => '2024-12-03 17:11:27',
            ),
            23 => 
            array (
                'id' => 24,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 3,
                'field' => 'status',
                'from' => NULL,
                'to' => 'revisión',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"cp": {"new": "Tempore v", "old": null}, "id": {"new": 3, "old": null}, "rfc": {"new": "08909789", "old": null}, "state": {"new": "Et labore odit id nisi distinctio Mollitia deserunt alias", "old": null}, "number": {"new": "851", "old": null}, "status": {"new": "revisión", "old": null}, "street": {"new": "Sed anim et et dicta iure quibusdam praesentium rem natus", "old": null}, "country": {"new": "Consequatur Enim nisi culpa deserunt tempora esse iste molestias aut quidem et", "old": null}, "created_at": {"new": "2024-12-03 17:12:14", "old": null}, "updated_at": {"new": "2024-12-03 17:12:14", "old": null}, "web_company": {"new": "Gaines and Ward LLC", "old": null}, "company_name": {"new": "proveerdor 3", "old": null}, "municipality": {"new": "Sint eu laborum aut fuga Duis dolores laboriosam necessitatibus molestias", "old": null}, "neighborhood": {"new": "Alias nulla explicabo Dolor labore et fugiat non ipsum dolor officiis dignissimos id", "old": null}, "user_request_id": {"new": 274, "old": null}}',
                'created_at' => '2024-12-03 17:12:14',
                'updated_at' => '2024-12-03 17:12:14',
            ),
            24 => 
            array (
                'id' => 25,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'rechazado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 52,
                'changed_attributes' => '{"status": {"new": "rechazado", "old": "revisión"}}',
                'created_at' => '2024-12-03 17:12:45',
                'updated_at' => '2024-12-03 17:12:45',
            ),
            25 => 
            array (
                'id' => 26,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'rechazado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 52,
                'changed_attributes' => '{"status": {"new": "rechazado", "old": "revisión"}}',
                'created_at' => '2024-12-03 17:12:58',
                'updated_at' => '2024-12-03 17:12:58',
            ),
            26 => 
            array (
                'id' => 27,
                'model_type' => 'App\\Models\\PurchaseProvider',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 52,
                'changed_attributes' => '{"status": {"new": "aprobado", "old": "revisión"}}',
                'created_at' => '2024-12-03 17:13:10',
                'updated_at' => '2024-12-03 17:13:10',
            ),
            27 => 
            array (
                'id' => 28,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "16", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "89", "old": null}, "use_cfdi": {"new": "107-Comunicaciones satelitales", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-12-10 20:07:56", "old": null}, "updated_at": {"new": "2024-12-10 20:07:56", "old": null}, "provider_id": {"new": "3", "old": null}, "quote_folio": {"new": "Consectetur tempor ", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "Qui laboriosam aut ", "old": null}, "term_payment": {"new": "30 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": "27", "old": null}, "retention_iva": {"new": "50", "old": null}, "requisition_id": {"new": "1", "old": null}, "shipping_method": {"new": "Ut labore ab sit di", "old": null}, "condition_payment": {"new": "Rerum magna voluptas", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "retention_another": {"new": "25", "old": null}, "final_delivery_date": {"new": "2024-12-12", "old": null}, "initial_delivery_date": {"new": "2024-12-10", "old": null}}',
                'created_at' => '2024-12-10 20:07:56',
                'updated_at' => '2024-12-10 20:07:56',
            ),
            28 => 
            array (
                'id' => 29,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "0", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "6200", "old": null}, "use_cfdi": {"new": "108-Otra maquinaria y equipo", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2024-12-11 15:37:13", "old": null}, "updated_at": {"new": "2024-12-11 15:37:13", "old": null}, "provider_id": {"new": "3", "old": null}, "quote_folio": {"new": "Excepteur cum asperi", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "Voluptas vel aliquid", "old": null}, "term_payment": {"new": "45 días", "old": null}, "type_payment": {"new": "PPD - Pago en parcialidades o diferido", "old": null}, "retention_isr": {"new": "96", "old": null}, "retention_iva": {"new": "70", "old": null}, "requisition_id": {"new": "1", "old": null}, "shipping_method": {"new": "Porro amet enim nob", "old": null}, "condition_payment": {"new": "Tenetur qui sit ut a", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "retention_another": {"new": "64", "old": null}, "final_delivery_date": {"new": "2024-12-12", "old": null}, "initial_delivery_date": {"new": "2024-12-11", "old": null}}',
                'created_at' => '2024-12-11 15:37:13',
                'updated_at' => '2024-12-11 15:37:13',
            ),
            29 => 
            array (
                'id' => 30,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2024-12-17 15:42:29',
                'updated_at' => '2024-12-17 15:42:29',
            ),
            30 => 
            array (
                'id' => 31,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2024-12-17 17:28:46',
                'updated_at' => '2024-12-17 17:28:46',
            ),
            31 => 
            array (
                'id' => 32,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2024-12-17 19:43:08',
                'updated_at' => '2024-12-17 19:43:08',
            ),
        ));
        
        
    }
}