<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class StateHistoriesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('state_histories')->delete();
        
        \DB::table('state_histories')->insert(array (
            0 => 
            array (
                'id' => 50,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "G-ISW-2025-0001", "old": null}, "motive": {"new": "Sapiente mollit quos nostrum qui saepe pariatur Ad quasi eum dolore cum natus", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-21 16:01:12", "old": null}, "project_id": {"new": "2", "old": null}, "updated_at": {"new": "2025-01-21 16:01:12", "old": null}, "observation": {"new": "Elit enim in magni molestiae beatae voluptas quis et maiores qui in id dolor aliquip quod a corporis itaque facilis", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-22 00:00:00", "old": null}, "delivery_address": {"new": "Eveniet molestiae sunt impedit veniam pariatur Et voluptatibus fugit qui commodo consequatur", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-21 16:01:12',
                'updated_at' => '2025-01-21 16:01:12',
            ),
            1 => 
            array (
                'id' => 51,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-21 16:01:44',
                'updated_at' => '2025-01-21 16:01:44',
            ),
            2 => 
            array (
                'id' => 52,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "G-ISW-2025-0002", "old": null}, "motive": {"new": "Iste ex harum autem omnis laboris non et non eum possimus nulla harum sed saepe nulla amet incidunt ratione ut", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-21 16:03:57", "old": null}, "project_id": {"new": "4", "old": null}, "updated_at": {"new": "2025-01-21 16:03:57", "old": null}, "observation": {"new": "Laboriosam nisi quis quos quis possimus consectetur minim ab pariatur Commodo minim eum qui dolorem accusamus irure", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-22 00:00:00", "old": null}, "delivery_address": {"new": "Et eius tempora eius molestiae", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-21 16:03:57',
                'updated_at' => '2025-01-21 16:03:57',
            ),
            3 => 
            array (
                'id' => 53,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-21 16:16:18',
                'updated_at' => '2025-01-21 16:16:18',
            ),
            4 => 
            array (
                'id' => 54,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 3, "old": null}, "folio": {"new": "G-ISW-2025-0003", "old": null}, "motive": {"new": "Ut obcaecati id in eu omnis est", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-21 16:17:39", "old": null}, "project_id": {"new": "4", "old": null}, "updated_at": {"new": "2025-01-21 16:17:39", "old": null}, "observation": {"new": "Non consequat Et ullam qui cupiditate eos accusamus est optio cupiditate minim sunt nisi", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-22 00:00:00", "old": null}, "delivery_address": {"new": "Voluptatibus commodi ea suscipit earum cum consequuntur quae", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-21 16:17:39',
                'updated_at' => '2025-01-21 16:17:39',
            ),
            5 => 
            array (
                'id' => 55,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-21 16:24:53',
                'updated_at' => '2025-01-21 16:24:53',
            ),
            6 => 
            array (
                'id' => 56,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"id": {"new": 4, "old": null}, "folio": {"new": "G-ISW-2025-0004", "old": null}, "motive": {"new": "Necessitatibus possimus et eius autem voluptatem voluptatem provident nihil suscipit voluptatem tempor", "old": null}, "status": {"new": "borrador", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-21 16:25:11", "old": null}, "project_id": {"new": "3", "old": null}, "updated_at": {"new": "2025-01-21 16:25:11", "old": null}, "observation": {"new": "Rem aut quibusdam vel architecto quasi dolorum molestias nostrum sint nihil culpa in sit reprehenderit", "old": null}, "confidential": {"new": false, "old": null}, "date_delivery": {"new": "2025-01-23 00:00:00", "old": null}, "delivery_address": {"new": "Deleniti sed earum saepe occaecat", "old": null}, "approval_chain_id": {"new": 2, "old": null}}',
                'created_at' => '2025-01-21 16:25:11',
                'updated_at' => '2025-01-21 16:25:11',
            ),
            7 => 
            array (
                'id' => 57,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión por almacén',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión por almacén", "old": "borrador"}}',
                'created_at' => '2025-01-21 16:25:51',
                'updated_at' => '2025-01-21 16:25:51',
            ),
            8 => 
            array (
                'id' => 58,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-21 16:28:42',
                'updated_at' => '2025-01-21 16:28:42',
            ),
            9 => 
            array (
                'id' => 59,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-21 16:28:48',
                'updated_at' => '2025-01-21 16:28:48',
            ),
            10 => 
            array (
                'id' => 60,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-21 16:28:55',
                'updated_at' => '2025-01-21 16:28:55',
            ),
            11 => 
            array (
                'id' => 61,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión por almacén',
                'to' => 'revisión',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 199,
                'changed_attributes' => '{"status": {"new": "revisión", "old": "revisión por almacén"}}',
                'created_at' => '2025-01-21 16:29:24',
                'updated_at' => '2025-01-21 16:29:24',
            ),
            12 => 
            array (
                'id' => 62,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 152,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-21 16:34:30',
                'updated_at' => '2025-01-21 16:34:30',
            ),
            13 => 
            array (
                'id' => 63,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 152,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-21 16:34:37',
                'updated_at' => '2025-01-21 16:34:37',
            ),
            14 => 
            array (
                'id' => 64,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 152,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-21 16:34:44',
                'updated_at' => '2025-01-21 16:34:44',
            ),
            15 => 
            array (
                'id' => 65,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión',
                'to' => 'aprobado por revisor',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 152,
                'changed_attributes' => '{"status": {"new": "aprobado por revisor", "old": "revisión"}}',
                'created_at' => '2025-01-21 16:34:51',
                'updated_at' => '2025-01-21 16:34:51',
            ),
            16 => 
            array (
                'id' => 66,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-21 16:35:09',
                'updated_at' => '2025-01-21 16:35:09',
            ),
            17 => 
            array (
                'id' => 67,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-21 16:35:16',
                'updated_at' => '2025-01-21 16:35:16',
            ),
            18 => 
            array (
                'id' => 68,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-21 16:35:22',
                'updated_at' => '2025-01-21 16:35:22',
            ),
            19 => 
            array (
                'id' => 69,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por revisor',
                'to' => 'aprobado por gerencia',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerencia", "old": "aprobado por revisor"}}',
                'created_at' => '2025-01-21 16:35:28',
                'updated_at' => '2025-01-21 16:35:28',
            ),
            20 => 
            array (
                'id' => 70,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-21 16:35:47',
                'updated_at' => '2025-01-21 16:35:47',
            ),
            21 => 
            array (
                'id' => 71,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-21 16:35:54',
                'updated_at' => '2025-01-21 16:35:54',
            ),
            22 => 
            array (
                'id' => 72,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-21 16:36:00',
                'updated_at' => '2025-01-21 16:36:00',
            ),
            23 => 
            array (
                'id' => 73,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerencia',
                'to' => 'aprobado por DG',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG", "old": "aprobado por gerencia"}}',
                'created_at' => '2025-01-21 16:36:07',
                'updated_at' => '2025-01-21 16:36:07',
            ),
            24 => 
            array (
                'id' => 74,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 4,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-21 16:37:06',
                'updated_at' => '2025-01-21 16:37:06',
            ),
            25 => 
            array (
                'id' => 75,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 3,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-21 16:39:05',
                'updated_at' => '2025-01-21 16:39:05',
            ),
            26 => 
            array (
                'id' => 76,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-21 16:41:10',
                'updated_at' => '2025-01-21 16:41:10',
            ),
            27 => 
            array (
                'id' => 77,
                'model_type' => 'App\\Models\\PurchaseRequisition',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por DG',
                'to' => 'comprador asignado',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "comprador asignado", "old": "aprobado por DG"}}',
                'created_at' => '2025-01-21 16:41:24',
                'updated_at' => '2025-01-21 16:41:24',
            ),
            28 => 
            array (
                'id' => 78,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 1, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "0", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "105-Dados, troqueles, moldes, matrices y herramental", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-21 17:18:31", "old": null}, "updated_at": {"new": "2025-01-21 17:18:31", "old": null}, "provider_id": {"new": "297", "old": null}, "quote_folio": {"new": "Sapiente sed dolore ", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "test", "old": null}, "term_payment": {"new": "30 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "4", "old": null}, "shipping_method": {"new": "Tenetur cumque place", "old": null}, "delivery_address": {"new": "Almacén, Av. Santa Mónica No.33, Col El Mirador, Tlalnepantla de Baz, Estado de México 54080.", "old": null}, "condition_payment": {"new": "Sint maxime alias of", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "final_delivery_date": {"new": "2025-01-24", "old": null}, "provider_contact_id": {"new": "205", "old": null}, "initial_delivery_date": {"new": "2025-01-22", "old": null}, "documentation_delivery": {"new": "[{\\"name\\":\\"Copia de remisi\\\\u00f3n y\\\\/o Factura\\"},{\\"name\\":\\"Orden de compra\\"},{\\"name\\":\\"Certificados de calidad\\"}]", "old": null}}',
                'created_at' => '2025-01-21 17:18:31',
                'updated_at' => '2025-01-21 17:18:31',
            ),
            29 => 
            array (
                'id' => 79,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-21 17:35:02',
                'updated_at' => '2025-01-21 17:35:02',
            ),
            30 => 
            array (
                'id' => 80,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-21 17:50:52',
                'updated_at' => '2025-01-21 17:50:52',
            ),
            31 => 
            array (
                'id' => 81,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-21 18:06:11',
                'updated_at' => '2025-01-21 18:06:11',
            ),
            32 => 
            array (
                'id' => 82,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 1,
                'field' => 'status',
                'from' => 'aprobado por gerente solicitante',
                'to' => 'autorizada para proveedor',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "autorizada para proveedor", "old": "aprobado por gerente solicitante"}}',
                'created_at' => '2025-01-21 18:41:36',
                'updated_at' => '2025-01-21 18:41:36',
            ),
            33 => 
            array (
                'id' => 83,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 2, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "16", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "101-Construcciones", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-22 15:04:00", "old": null}, "updated_at": {"new": "2025-01-22 15:04:00", "old": null}, "provider_id": {"new": "299", "old": null}, "quote_folio": {"new": "Sapiente perferendis", "old": null}, "form_payment": {"new": "transferencia", "old": null}, "observations": {"new": "test", "old": null}, "term_payment": {"new": "30 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "4", "old": null}, "shipping_method": {"new": "Aut dicta architecto", "old": null}, "delivery_address": {"new": "Almacén, Av. Santa Mónica No.33, Col El Mirador, Tlalnepantla de Baz, Estado de México 54080.", "old": null}, "condition_payment": {"new": "Hic rem ipsa aliqua", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "final_delivery_date": {"new": "2025-01-24", "old": null}, "provider_contact_id": {"new": "208", "old": null}, "initial_delivery_date": {"new": "2025-01-23", "old": null}, "documentation_delivery": {"new": "[{\\"name\\":\\"Copia de remisi\\\\u00f3n y\\\\/o Factura\\"},{\\"name\\":\\"Orden de compra\\"},{\\"name\\":\\"Certificados de calidad\\"}]", "old": null}}',
                'created_at' => '2025-01-22 15:04:00',
                'updated_at' => '2025-01-22 15:04:00',
            ),
            34 => 
            array (
                'id' => 84,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-22 15:04:22',
                'updated_at' => '2025-01-22 15:04:22',
            ),
            35 => 
            array (
                'id' => 85,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-22 15:05:42',
                'updated_at' => '2025-01-22 15:05:42',
            ),
            36 => 
            array (
                'id' => 86,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 2,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-22 15:07:36',
                'updated_at' => '2025-01-22 15:07:36',
            ),
            37 => 
            array (
                'id' => 87,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 3,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 3, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "8", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "104-Equipo de cómputo y accesorios", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-22 17:49:47", "old": null}, "updated_at": {"new": "2025-01-22 17:49:47", "old": null}, "provider_id": {"new": "297", "old": null}, "quote_folio": {"new": "Ad a dignissimos quo", "old": null}, "form_payment": {"new": "efectivo", "old": null}, "observations": {"new": "prueba", "old": null}, "term_payment": {"new": "60 días", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "4", "old": null}, "shipping_method": {"new": "Quos porro praesenti", "old": null}, "delivery_address": {"new": "Almacén, Av. Santa Mónica No.33, Col El Mirador, Tlalnepantla de Baz, Estado de México 54080.", "old": null}, "condition_payment": {"new": "Alias adipisci eum e", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "final_delivery_date": {"new": "2025-01-23", "old": null}, "provider_contact_id": {"new": "205", "old": null}, "initial_delivery_date": {"new": "2025-01-23", "old": null}, "documentation_delivery": {"new": "[{\\"name\\":\\"Copia de remisi\\\\u00f3n y\\\\/o Factura\\"},{\\"name\\":\\"Orden de compra\\"},{\\"name\\":\\"Certificados de calidad\\"}]", "old": null}}',
                'created_at' => '2025-01-22 17:49:47',
                'updated_at' => '2025-01-22 17:49:47',
            ),
            38 => 
            array (
                'id' => 88,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 4,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 4, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "16", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "102-Mobiliario y equipo de oficina por inversiones", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-22 17:53:44", "old": null}, "updated_at": {"new": "2025-01-22 17:53:44", "old": null}, "provider_id": {"new": "297", "old": null}, "quote_folio": {"new": "Et in omnis ut magna", "old": null}, "form_payment": {"new": "efectivo", "old": null}, "observations": {"new": "prueba", "old": null}, "term_payment": {"new": "45 días", "old": null}, "type_payment": {"new": "PPD - Pago en parcialidades o diferido", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "3", "old": null}, "shipping_method": {"new": "Commodi dolore perfe", "old": null}, "delivery_address": {"new": "Almacén, Av. Santa Mónica No.33, Col El Mirador, Tlalnepantla de Baz, Estado de México 54080.", "old": null}, "condition_payment": {"new": "Eiusmod necessitatib", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "final_delivery_date": {"new": "2025-01-24", "old": null}, "provider_contact_id": {"new": "205", "old": null}, "initial_delivery_date": {"new": "2025-01-23", "old": null}, "documentation_delivery": {"new": "[{\\"name\\":\\"Copia de remisi\\\\u00f3n y\\\\/o Factura\\"},{\\"name\\":\\"Orden de compra\\"},{\\"name\\":\\"Certificados de calidad\\"}]", "old": null}}',
                'created_at' => '2025-01-22 17:53:44',
                'updated_at' => '2025-01-22 17:53:44',
            ),
            39 => 
            array (
                'id' => 89,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'field' => 'status',
                'from' => NULL,
                'to' => 'borrador',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"id": {"new": 5, "old": null}, "folio": {"new": "N/A", "old": null}, "status": {"new": "borrador", "old": null}, "tax_iva": {"new": "8", "old": null}, "currency": {"new": "MXN", "old": null}, "discount": {"new": "0", "old": null}, "use_cfdi": {"new": "G03-Gastos en general", "old": null}, "company_id": {"new": 1, "old": null}, "created_at": {"new": "2025-01-22 17:55:00", "old": null}, "updated_at": {"new": "2025-01-22 17:55:00", "old": null}, "provider_id": {"new": "297", "old": null}, "quote_folio": {"new": "Rerum adipisicing la", "old": null}, "form_payment": {"new": "efectivo", "old": null}, "observations": {"new": "p", "old": null}, "term_payment": {"new": "contado", "old": null}, "type_payment": {"new": "PUE - Pago en una sola exhibición", "old": null}, "retention_isr": {"new": 0, "old": null}, "retention_iva": {"new": 0, "old": null}, "requisition_id": {"new": "3", "old": null}, "shipping_method": {"new": "Dolorem eiusmod inci", "old": null}, "delivery_address": {"new": "Almacén, Av. Santa Mónica No.33, Col El Mirador, Tlalnepantla de Baz, Estado de México 54080.", "old": null}, "condition_payment": {"new": "Quos maiores dolor p", "old": null}, "purchaser_user_id": {"new": 274, "old": null}, "final_delivery_date": {"new": "2025-01-24", "old": null}, "provider_contact_id": {"new": "205", "old": null}, "initial_delivery_date": {"new": "2025-01-23", "old": null}, "documentation_delivery": {"new": "[{\\"name\\":\\"Copia de remisi\\\\u00f3n y\\\\/o Factura\\"},{\\"name\\":\\"Orden de compra\\"},{\\"name\\":\\"Certificados de calidad\\"}]", "old": null}}',
                'created_at' => '2025-01-22 17:55:00',
                'updated_at' => '2025-01-22 17:55:00',
            ),
            40 => 
            array (
                'id' => 90,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'field' => 'status',
                'from' => 'borrador',
                'to' => 'revisión gerente de compras',
                'custom_properties' => '[]',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 274,
                'changed_attributes' => '{"status": {"new": "revisión gerente de compras", "old": "borrador"}}',
                'created_at' => '2025-01-22 18:08:21',
                'updated_at' => '2025-01-22 18:08:21',
            ),
            41 => 
            array (
                'id' => 91,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'field' => 'status',
                'from' => 'revisión gerente de compras',
                'to' => 'aprobado por gerente de compras',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 180,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente de compras", "old": "revisión gerente de compras"}}',
                'created_at' => '2025-01-22 18:09:07',
                'updated_at' => '2025-01-22 18:09:07',
            ),
            42 => 
            array (
                'id' => 92,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'field' => 'status',
                'from' => 'aprobado por gerente de compras',
                'to' => 'aprobado por gerente solicitante',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 331,
                'changed_attributes' => '{"status": {"new": "aprobado por gerente solicitante", "old": "aprobado por gerente de compras"}}',
                'created_at' => '2025-01-22 18:09:57',
                'updated_at' => '2025-01-22 18:09:57',
            ),
            43 => 
            array (
                'id' => 93,
                'model_type' => 'App\\Models\\PurchaseOrder',
                'model_id' => 5,
                'field' => 'status',
                'from' => 'aprobado por gerente solicitante',
                'to' => 'aprobado por DG nivel 1',
                'custom_properties' => '{"respuesta": null}',
                'responsible_type' => 'App\\Models\\User',
                'responsible_id' => 106,
                'changed_attributes' => '{"status": {"new": "aprobado por DG nivel 1", "old": "aprobado por gerente solicitante"}}',
                'created_at' => '2025-01-22 18:10:29',
                'updated_at' => '2025-01-22 18:10:29',
            ),
        ));
        
        
    }
}