<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 13,
                'name' => 'Alcántara Bautista Benjamín',
                'email' => 'balcantarab@gptservices.com',
            'phone' => '(+52) 55 8096 0795',
                'depto' => 'Logística',
                'puesto' => 'Ayudante Especializado',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:31',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            1 =>
            array (
                'id' => 14,
                'name' => 'Becerra Yebra Jesús',
                'email' => 'jbecerray@gptservices.com',
            'phone' => '(+52) 55 3034 8643',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Soldador Master',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'w4WWHBjtISuM1RL9TPcEKoD82khdTZowJ6y4HOATZGcuauK1WexIB01qeYq8',
                'created_at' => '2022-08-06 08:33:31',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            2 =>
            array (
                'id' => 18,
                'name' => 'López Arreola Ana Lilia',
                'email' => 'alopeza@gptservices.com',
            'phone' => '(+52) 55 8108 6378',
                'depto' => 'Servicios Generales',
                'puesto' => 'Encargada Administrativa',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            3 =>
            array (
                'id' => 19,
                'name' => 'García Arroyo Rafael',
                'email' => 'rgarciaa@gptservices.com',
                'phone' => '',
                'depto' => 'Ingeniería',
                'puesto' => 'Gerencia de Ingeniería y Manufactura',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'waWCRVorwFO69uYPWVrZTMPgtJKklHuSbXjOfxqH2hhXP5wnL80XFiuMsKm0',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            4 =>
            array (
                'id' => 22,
                'name' => 'Ponce Reyes Iván',
                'email' => 'iponcer@gptservices.com',
            'phone' => '(+52) 55 8103 0124',
                'depto' => 'HT & LS',
                'puesto' => 'Técnico Especialista en HT & LS Nivel III',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '3jZf79bjgNY0AOKZpyCciSpbdcnXqwrAl7rpwq9moPikgG261GTb9ah4FWTQ',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            5 =>
            array (
                'id' => 26,
                'name' => 'Ulloa Tello Sinhue',
                'email' => 'sulloat@gptservices.com',
            'phone' => '(+52) 55 5953 7883',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Especialista en Soldadura',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            6 =>
            array (
                'id' => 36,
                'name' => 'Gutiérrez Melo Guillermo',
                'email' => 'ggutierrezm@gptservices.com',
            'phone' => '(+52) 55 8097 1226',
                'depto' => 'Proyectos',
                'puesto' => 'Gerencia de Proyectos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            7 =>
            array (
                'id' => 37,
                'name' => 'Reyes Yáñez Luis',
                'email' => 'lreyesy@gptservices.com',
                'phone' => '',
                'depto' => 'Manufactura',
                'puesto' => 'Mecánico Tornero',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            8 =>
            array (
                'id' => 40,
                'name' => 'Basave Arce Fernando',
                'email' => 'febasavea@gptservices.com',
                'phone' => '',
                'depto' => 'Contratos',
                'puesto' => 'Gerencia de Contratos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '9M7wmI6yHByYaZNs7GxzociptJrLzt9NK6ZjKiRSwId1xMGZ5058pOdHxQlT',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            9 =>
            array (
                'id' => 46,
                'name' => 'García Montiel Aquiles Gonzalo',
                'email' => 'agarciam@gptservices.com',
            'phone' => '(+52) 55 5965 6833',
                'depto' => 'Comercial',
                'puesto' => 'Gerencia Comercial',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            10 =>
            array (
                'id' => 50,
                'name' => 'Cruz Báez Aurelio',
                'email' => 'acruzb@gptservices.com',
            'phone' => '(+52) 55 7667 3044',
                'depto' => 'HT & LS',
                'puesto' => 'Técnico Especialista en HT & LS Nivel I',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '0wfLKvQ0LS92zEChBrxVGTDREdngfTKy8VUMIygmz86zA4lOY6jkMLvrafdo',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            11 =>
            array (
                'id' => 52,
                'name' => 'Pereyra Medina Norma Angélica',
                'email' => 'npereyram@gptservices.com',
                'phone' => '55 1954 4768',
                'depto' => 'Compras',
                'puesto' => 'Comprador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '4uJngJx7ByzxzWlj7FaJ6GLhAgf61FxTVOVYWzHQvO5MBgLEaqWiY6lMi2To',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-21 02:34:31',
                'management_id' =>null,
            ),
            12 =>
            array (
                'id' => 53,
                'name' => 'González Huitrón Adriana',
                'email' => 'agonzalezh@gptservices.com',
                'phone' => '',
                'depto' => 'Ingeniería',
                'puesto' => 'Gerencia de Ingeniería',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$12$GWGpw4wUXzcrJrWt1v6aWO/p0RsC5CZAbW7G4wOqO0i5SDTy/q9.m',
                'remember_token' => '8ZBq76N2nVj3H2TZ68QShGKVITZ6846sVbOgit6cuW4n0qjW88HCnblOKDht',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            13 =>
            array (
                'id' => 64,
                'name' => 'Sandoval Cabello Luis',
                'email' => 'lsandovalc@gptservices.com',
                'phone' => '',
                'depto' => 'Mantenimiento',
                'puesto' => 'Mecánico Especialista',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            14 =>
            array (
                'id' => 67,
                'name' => 'Santoyo Meléndez Luis Javier',
                'email' => 'ljsantoyom@gptservices.com',
            'phone' => '(+52) 55 8222 7624',
                'depto' => 'Comercial',
                'puesto' => 'Dirección de Desarrollo de Nuevos Negocios',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            15 =>
            array (
                'id' => 89,
                'name' => 'Jiménez Camacho Juan',
                'email' => 'jjimenezc@gptservices.com',
            'phone' => '(+52) 4721 270293',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            16 =>
            array (
                'id' => 92,
                'name' => 'Acosta Arroyo Néstor Adair',
                'email' => 'naacostaa@gptservices.com',
                'phone' => '',
                'depto' => 'HT & LS',
                'puesto' => 'Técnico Especialista en HT & LS Nivel II',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            17 =>
            array (
                'id' => 99,
                'name' => 'Rodríguez Guzmán Raúl',
                'email' => 'rrodriguezg@gptservices.com',
            'phone' => '(+52) 55 3513 4163',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            18 =>
            array (
                'id' => 106,
                'name' => 'Reyes Ramírez Denise Marisol',
                'email' => 'dmreyesr@gptservices.com',
                'phone' => '55 8097 1232',
                'depto' => 'Dirección General',
                'puesto' => 'Dirección General',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'MeWfEv5cYrS2QqsLw7mtjWW1rY19HOddOo4WmJjBKF6kP7Jm27E2S1hBC6O0',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-21 02:21:58',
                'management_id' =>null,
            ),
            19 =>
            array (
                'id' => 114,
                'name' => 'Ríos Cuautitla Manuel Antonio',
                'email' => 'mariosc@gptservices.com',
                'phone' => '',
                'depto' => 'Ingeniería',
                'puesto' => 'Ingeniería',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'sUjlIuJvcLbACRoF9FVFYV4UHm48jnPXGHQHoyQTUVJyabtmMy9YxTDlBI26',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            20 =>
            array (
                'id' => 120,
                'name' => 'González Muñoz Roberto',
                'email' => 'rgonzalezm@gptservices.com',
                'phone' => '',
                'depto' => 'Manufactura',
                'puesto' => 'Manufactura',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            21 =>
            array (
                'id' => 123,
                'name' => 'Salgado Zúñiga Angélica',
                'email' => 'asalgadoz@gptservices.com',
            'phone' => '(+52) 55 6703 9366',
                'depto' => 'recursos Humanos',
                'puesto' => 'Recursos Humanos Sr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'pgDnFUQUDL1qnZecYNzNgYWA5i9dbCBVC47BfnvIroHntrf4piuzgGU5gbiS',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            22 =>
            array (
                'id' => 131,
                'name' => 'Martínez Segura Axel Javier',
                'email' => 'ajmartinezs@gptservices.com',
            'phone' => '(+52) 55 5188 2957',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            23 =>
            array (
                'id' => 132,
                'name' => 'Paes Santillán Martín',
                'email' => 'mpaess@gptservices.com',
            'phone' => '(+52) 55 7786 2987',
                'depto' => 'Soldadura',
                'puesto' => 'Ayudante de Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'f0AOV4OeMxTlDd6DGbVhapjR5NbuVJmc94XKGfzTyiDGwAHFFWf4R0r28RAe',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            24 =>
            array (
                'id' => 137,
                'name' => 'Godínez Rivera Luis Jesús',
                'email' => 'lgodinez@gptservices.com',
                'phone' => '',
                'depto' => 'Mantenimiento',
                'puesto' => 'Mecánico Especialista',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '8I58h7xGfiaeVrRnqSKoAeUuxbPocj6uUd1vKvXrBvHdiE9QGE4QzBsuQtla',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            25 =>
            array (
                'id' => 152,
                'name' => 'Meza Rivera Edgar David',
                'email' => 'emeza@gptservices.com',
            'phone' => '(+52) 55 2280 0751',
                'depto' => 'IT',
                'puesto' => 'Soporte Técnico IT',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'C9RhycUSKUHfCvG9SejIjs5LqZXnty6GyK6RH6kHHcSUsfGMm0OY23rV1VlB',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            26 =>
            array (
                'id' => 157,
                'name' => 'Pérez Hernández Claudio Magdaleno',
                'email' => 'cperez@gptservices.com',
            'phone' => '(+52) 55 8531 7147',
                'depto' => 'HT & LS',
                'puesto' => 'Trainee HT & LS',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            27 =>
            array (
                'id' => 158,
                'name' => 'Colín Antonio Yanet Rosario',
                'email' => 'yrcolina@gptservices.com',
            'phone' => '(+52) 55 2283 7096',
                'depto' => 'Finanzas ',
                'puesto' => 'Contador Sr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'GKcKYXFtNydxvhpYo0ymBjJJ4URtJEkc2tF4Elxabl9xEHaNo4RSiKbOTWKP',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            28 =>
            array (
                'id' => 166,
                'name' => 'Jiménez Ávila Rafael Alejandro',
                'email' => 'rajimeneza@gptservices.com',
            'phone' => '(+52) 55 5953 0834',
                'depto' => 'Finanzas ',
                'puesto' => 'Contador Jr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'FkpHLVIdWKaJPN8sJRxGMpeld0zLD3VFPV4qvkkmEhuKMfTtPeUoxQaRBvql',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            29 =>
            array (
                'id' => 168,
                'name' => 'Ordaz Espinosa Sergio Antonio',
                'email' => 'santonio@gptservices.com',
            'phone' => '(+52) 55 5103 5335',
                'depto' => 'Comercial',
                'puesto' => 'Gerencia Comercial',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            30 =>
            array (
                'id' => 180,
                'name' => 'García Ojeda Jorge Eduardo',
                'email' => 'jegarciao@gptservices.com',
            'phone' => '(+52) 55 30 40 90 54',
                'depto' => 'Compras',
                'puesto' => 'Encargado de compras',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'mGemTVITiJlLHYV9O6Zbg6Fh4aqWq0uIKLvp42koxFoF5fxTyIhqt951ZBEI',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            31 =>
            array (
                'id' => 187,
                'name' => 'Ramírez Pérez Alejandro Aldair',
                'email' => 'aramirezp@gptservices.com',
            'phone' => '(+52) 55 83 59 05 08',
                'depto' => 'Proyectos',
                'puesto' => 'Ingeniero de Costos Jr.',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'yEimbHQGbd5h3VvD7R8wh5AVKoTlX6xMlmV7VztuXcLmtiQkQ1x0ZnB2S5XD',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            32 =>
            array (
                'id' => 191,
                'name' => 'Martínez Jarquín Jennifer',
                'email' => 'jmartinezj@gptservices.com',
            'phone' => '(+52) 55 74 99 89 47',
                'depto' => 'Ingeniería',
                'puesto' => 'Diseñador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            33 =>
            array (
                'id' => 192,
                'name' => 'Díaz Esparza Karla Cristina',
                'email' => 'kdiaze@gptservices.com',
            'phone' => '(+52) 55 44 55 67 72',
                'depto' => 'QHSE',
                'puesto' => 'Trainee de HSE',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'nIT5zlk1R8tm9kMNDofJTRXmQxocxFVWAbD46D1qlLhi9trIepvNUgvYhV5k',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            34 =>
            array (
                'id' => 193,
                'name' => 'Martínez Hernández Martín Alejandro',
                'email' => 'mmartinez@gptservices.com',
            'phone' => '(+52) 56 19 43 95 09',
                'depto' => 'Servicios Generales',
                'puesto' => 'Servicios Generales Sr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'Hhb0Ue3nHZu7LTgC48u6GI1Uojy5VOR7BobKn16mKCMYIkW1sdxzF6ntyQb5',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            35 =>
            array (
                'id' => 199,
                'name' => 'Hernández Mendoza Alan Etzahu',
                'email' => 'ahernandezm@gptservices.com',
                'phone' => '5540756374',
                'depto' => 'IT',
                'puesto' => 'Trainee de IT',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$12$S0mLRDTEiOAp4xyZatp8k.7bctoyOGjpXKlX/.JnEsD4D6DHluq3W',
                'remember_token' => '18BaaMWoIgXK6hXdDnNsXlDJaSupPv2KVAhpkZFgr6u6UB9cglyWciRfz4w5',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-21 01:11:46',
                'management_id' =>null,
            ),
            36 =>
            array (
                'id' => 200,
                'name' => 'Rojas González Rocío',
                'email' => 'rrojasg@gptservices.com',
            'phone' => '(+52) 5591862465',
                'depto' => 'QHSE',
                'puesto' => 'Trainee de Calidad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'Xwr35wkG1LHTBB9N61SKAKxvBnCQg75NgEm3RtslBHrpdhjlmPwePx72drB9',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            37 =>
            array (
                'id' => 202,
                'name' => 'González García Daniel',
                'email' => '',
            'phone' => '(+52) 55 11 79 61 70',
                'depto' => 'Servicios Generales',
                'puesto' => 'Limpieza',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            38 =>
            array (
                'id' => 205,
                'name' => 'López Olvera Erik David',
                'email' => 'edlopezo@gptservices.com',
            'phone' => '(+52) 55 81 29 09 74',
                'depto' => 'HT & LS',
                'puesto' => 'Trainee HT & LS',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            39 =>
            array (
                'id' => 212,
                'name' => 'Villafranca García Enrique',
                'email' => 'evillafranca@gptservices.com',
            'phone' => '(+52) 55 45 94 36 60',
                'depto' => 'Mantenimiento',
                'puesto' => 'Ayudante de Mantenimiento',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'uEouLW94avUuLRGRklFHZtpIP7VnZg2CG47vGobitXaeP7MSpUAoesmxB1ap',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            40 =>
            array (
                'id' => 223,
                'name' => 'Avilés Nieto José Héctor',
                'email' => 'haviles@gptservices.com',
                'phone' => '',
                'depto' => 'Servicios Generales',
                'puesto' => 'Servicios Generales Jr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            41 =>
            array (
                'id' => 227,
                'name' => 'Pérez Rodríguez Kevin Hazael',
                'email' => 'kperez@gptservices.com',
                'phone' => '',
                'depto' => 'Proyectos',
                'puesto' => 'Ingeniero de proyectos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'o4gpRz6iCKYYZNKnAFGVgzi0ENd5HKdckVyYKV88uvFTtwxipSHZmKOI0Kmz',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            42 =>
            array (
                'id' => 230,
                'name' => 'Bautista Cruz Ernesto',
                'email' => 'ebautista@gptservices.com',
                'phone' => '',
                'depto' => 'Servicios Generales',
                'puesto' => 'Servicios Generales Jr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'OdJAqOJ22GbqkmiLeGo8UU1fskGycn8kBQhDYUIz4A1k8bgDJrp8qlZHZn3y',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            43 =>
            array (
                'id' => 233,
                'name' => 'Correa Cruz Israel',
                'email' => 'icorrea@gptservices.com',
                'phone' => '',
                'depto' => 'Comercial',
                'puesto' => 'Ingeniero de Ventas',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-22 03:02:13',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            44 =>
            array (
                'id' => 235,
                'name' => 'Lugardo Aguilar Giovanni',
                'email' => '',
                'phone' => '',
                'depto' => 'Manufactura',
                'puesto' => 'Mecánico Tornero',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:25:13',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            45 =>
            array (
                'id' => 238,
                'name' => 'Ramón Zetina Karen Stefany',
                'email' => 'kramon@gptservices.com',
                'phone' => '',
                'depto' => 'Comercial',
                'puesto' => 'Trainee Comercial',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-10-24 01:51:36',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            46 =>
            array (
                'id' => 240,
                'name' => 'Pimentel García  Mónica Jazmín ',
                'email' => 'mpimentel@gptservices.com',
                'phone' => '',
                'depto' => 'Dirección General',
                'puesto' => 'Trainee de Marketing',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'k0yPZLZ4AU2fhaHJsM5CZnFk53TcXXINR33uWeppbkLMQAuEfFTzJrTuEBei',
                'created_at' => '2022-11-07 06:03:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            47 =>
            array (
                'id' => 244,
                'name' => 'Palafox Luna José Roberto',
                'email' => 'jpalafox@gptservices.com',
                'phone' => '',
                'depto' => 'Proyectos',
                'puesto' => 'Ingeniero de Costos Jr.',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'avqrOWEEbGErtZvYKz6WxBLT6SCivzNMvXSAaAQ66dN0Pz8iDStM3rz1c2qf',
                'created_at' => '2023-02-01 07:33:10',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            48 =>
            array (
                'id' => 247,
                'name' => 'Prado Hernández Juan Carlos',
                'email' => 'jprado@gptservices.com',
            'phone' => '(55)45570447',
                'depto' => 'Finanzas ',
                'puesto' => 'Trainee de Contabilidad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-02-15 02:30:34',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            49 =>
            array (
                'id' => 249,
                'name' => 'Salgado Rangel Rocío',
                'email' => 'rsalgado@gptservices.com',
            'phone' => '(+52) 55 8404 3368',
                'depto' => 'Manufactura',
                'puesto' => 'Ayudante de manufactura',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'FBR8IeKGInHG6ma3CRVfdtkusjBuwLunsjfGXd8xP5H6SG5GD3KQTBd1Zuaw',
                'created_at' => '2023-08-15 07:28:23',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            50 =>
            array (
                'id' => 250,
                'name' => 'Martínez Amador José Carlos',
                'email' => 'jmartinez@gptservices.com',
                'phone' => '56 2102 933',
                'depto' => 'Almacén',
                'puesto' => 'Ayudante de Almacén',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'LA9ZNIyB7ZyN6Q2JyJMc6d3EIjvhcWdVi5yJxC6IxjzZzBec4t61TUqkC1PT',
                'created_at' => '2023-03-08 02:40:15',
                'updated_at' => '2024-10-21 02:21:36',
                'management_id' =>null,
            ),
            51 =>
            array (
                'id' => 251,
                'name' => 'Rodríguez Vázquez Alejandro',
                'email' => 'arodriguez@gptservices.com',
                'phone' => '5544645133',
                'depto' => 'Servicios Generales',
                'puesto' => 'Chofer',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-03-07 22:36:46',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            52 =>
            array (
                'id' => 252,
                'name' => 'Mora Barrios Israel Omar',
                'email' => '',
                'phone' => '5586019168',
                'depto' => 'Soldadura',
                'puesto' => 'Ayudante de Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-03-07 22:48:55',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            53 =>
            array (
                'id' => 253,
                'name' => 'Nuñez Cruz Daniel',
                'email' => '',
                'phone' => '5613041196',
                'depto' => 'Mantenimiento',
                'puesto' => 'Ayudante de Manatenimiento',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-03-12 21:37:52',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            54 =>
            array (
                'id' => 256,
                'name' => 'Mendoza Gutierrez Rosa Maria',
                'email' => '',
                'phone' => '',
                'depto' => 'Servicios Generales',
                'puesto' => 'Limpieza',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:33:18',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            55 =>
            array (
                'id' => 257,
                'name' => 'Ramírez Jaimes Sergio Martín',
                'email' => 'sramirez@gptservices.com',
                'phone' => '',
                'depto' => 'Almacén',
                'puesto' => 'Maniobrista',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '2DxMh9e7myNgCeN80Q075Ku2Hqfbs61wn2My2xoXp63gUMxHtQMVlhd3WOcf',
                'created_at' => '2023-08-03 23:38:14',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            56 =>
            array (
                'id' => 258,
                'name' => 'Flores Valenzuela  Julia ',
                'email' => '',
                'phone' => '',
                'depto' => 'Servicios Generales',
                'puesto' => 'Limpieza',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:34:06',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            57 =>
            array (
                'id' => 260,
                'name' => 'Lázaro Juárez José de Jesús',
                'email' => 'jlazaro@gptservices.com',
                'phone' => '',
                'depto' => 'Manufactura y Mantenimiento',
                'puesto' => 'Ingeniero de Producto',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '$2y$12$Vqy869OdRhb.Y8V9p86iqumtUA83DZmrRu50i5W.iMHG7Pc84tjle',
                'remember_token' => 'B47xjqWtBzgZCrYjdzwwTUvSzxQkyPYTC4dERh2CW03YIcdQTzfWSziRfpjz',
                'created_at' => '2023-04-17 23:55:59',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            58 =>
            array (
                'id' => 263,
                'name' => 'García Real Joya Elizabeth',
                'email' => 'egarcia@gptservices.com',
                'phone' => '',
                'depto' => 'recursos Humanos',
                'puesto' => 'Recursos Humanos Jr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '6eqjMaenuwGw7EY89uzOY0CBpIkNlxPwYTiaxQ4uBAVIIbpB2WH10CizKi3f',
                'created_at' => '2023-05-01 20:03:40',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            59 =>
            array (
                'id' => 264,
                'name' => 'López Hernández Juan Carlos',
                'email' => 'jhernandez@gptservices.com',
                'phone' => '',
                'depto' => 'Servicios Generales',
                'puesto' => 'Auxiliar de mantenimiento',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'fIVwGNbOW0NTrWlcTMegiJ174TxsH0oF8ib928wphqOBLSa01bA7qlL3tws2',
                'created_at' => '2023-08-01 19:34:45',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            60 =>
            array (
                'id' => 265,
                'name' => 'Gómez López  Alfonso ',
                'email' => '',
                'phone' => '',
                'depto' => 'Mantenimiento',
                'puesto' => 'Pintor industrial',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:39:23',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            61 =>
            array (
                'id' => 266,
                'name' => 'Alvarado Bailey Omar',
                'email' => 'oalvarado@gptservices.com',
                'phone' => '',
                'depto' => 'Almacén',
                'puesto' => 'Ingeniero de Desarrollo',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'NLZE6VrmNTuNtLaLbs0Xs2UaJRDFVdY5TBCG8OFIWOQekxyLN5KiKvNu3fvD',
                'created_at' => '2023-05-16 02:01:12',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            62 =>
            array (
                'id' => 268,
                'name' => 'Carbajal Cerezo Carlos Ivan',
                'email' => '',
                'phone' => '',
                'depto' => 'Mantenimiento',
                'puesto' => 'Mecánico',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:45:16',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            63 =>
            array (
                'id' => 269,
                'name' => 'Santos Cruces Javier Mozart',
                'email' => 'jsantos@gptservices.com',
                'phone' => '',
                'depto' => 'Proyectos',
                'puesto' => 'Ingeniero de proyectos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'bDHRblbSfAIeqHIbDwuvZ5BXqBuGMYiq06jMa7lZ1ey6Goj07Xrq0UcSaH6b',
                'created_at' => '2023-06-26 05:11:03',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            64 =>
            array (
                'id' => 270,
                'name' => 'Orduña Álvarez Miguel Eduardo',
                'email' => 'eorduna@gptservices.com',
                'phone' => '',
                'depto' => 'HT & LS',
                'puesto' => 'Técnico Especialista en HT & LS Nivel II',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:48:21',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            65 =>
            array (
                'id' => 271,
                'name' => 'Cardona Salinas  José Manuel ',
                'email' => 'jcardona@gptservices.com',
                'phone' => '5610040567',
                'depto' => 'Logística',
                'puesto' => 'Operador de Grúa',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-15 07:50:07',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            66 =>
            array (
                'id' => 274,
                'name' => 'López Muñóz María Fernanda',
                'email' => 'mlopez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'compras',
                'puesto' => 'Comprador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-13 20:56:49',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            67 =>
            array (
                'id' => 275,
                'name' => 'Quechol Millán Agustín',
                'email' => 'NA',
                'phone' => 'NA',
                'depto' => 'Manufactura',
                'puesto' => 'Mecánico Tornero',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-08-29 20:08:40',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            68 =>
            array (
                'id' => 276,
                'name' => 'Paredes Chávez  Leonardo ',
                'email' => 'lparedes@gptservices.com',
                'phone' => 'NA',
                'depto' => 'Manufactura y Mantenimiento',
                'puesto' => 'Ingeniero de Producto',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-09-12 20:18:39',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            69 =>
            array (
                'id' => 277,
                'name' => 'Guevara Galán  Antonio ',
                'email' => 'guevaraantonio376@gmail.com',
                'phone' => '',
                'depto' => 'Seguridad Patrimonial',
                'puesto' => 'Guardia de seguridad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-09-17 23:58:57',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            70 =>
            array (
                'id' => 279,
                'name' => 'Alfaro Villegas Orlando Sebastian ',
                'email' => 'alfa0198@gmail.com',
                'phone' => 'NA',
                'depto' => 'Soldadura',
                'puesto' => 'Ayudante de Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-09-20 21:21:54',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            71 =>
            array (
                'id' => 282,
                'name' => 'Martínez Dolores  Diana ',
                'email' => 'dmartinez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'Finanzas ',
                'puesto' => 'Trainee de Contabilidad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2023-10-09 19:14:11',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            72 =>
            array (
                'id' => 285,
                'name' => 'Castañeda Martínez Juan Gabriel',
                'email' => 'NA',
                'phone' => '',
                'depto' => 'Seguridad Patrimonial',
                'puesto' => 'Guardia de seguridad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-01-03 03:38:48',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            73 =>
            array (
                'id' => 286,
                'name' => 'Pardo Sánchez Luis Enrique',
                'email' => 'NA',
                'phone' => '',
                'depto' => 'Manufactura',
                'puesto' => 'Tornero',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-01-17 20:50:12',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            74 =>
            array (
                'id' => 287,
                'name' => 'Moreno Carmona Eduardo',
                'email' => 'emoreno@gptservices.com',
                'phone' => 'NA',
                'depto' => 'Manufactura y Mantenimiento',
                'puesto' => 'Ingeniero de Producto',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'bRbnRqYrwV7EJat7zwwq1pp2vAWyQtfUfwP78ybOE4Z5Rdrv3hRc9fZrzs9I',
                'created_at' => '2024-01-11 21:41:48',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            75 =>
            array (
                'id' => 289,
                'name' => 'Raya Espino Miguel Ángel',
                'email' => 'NA',
                'phone' => 'NA',
                'depto' => 'Manufactura',
                'puesto' => 'Tornero',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-01-23 21:15:39',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            76 =>
            array (
                'id' => 290,
                'name' => 'Jiménez Ortega Mariana Karina',
                'email' => 'mjimenez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'Finanzas ',
                'puesto' => 'Trainee de Contabilidad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'Hz5wWBbN7whaLCEtQGvAzjer4BpF3dD99gdHaRmJwRKx6DpI5I9As6uM3xuO',
                'created_at' => '2024-01-31 17:12:57',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            77 =>
            array (
                'id' => 292,
                'name' => 'Zamora González Fernando',
                'email' => 'fzamora@gptservices.com',
                'phone' => 'NA',
                'depto' => 'Almacén',
                'puesto' => 'Almacenista',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'fzeOOKZaOyUG5E9IK9HGjyLaYkTuOJ2BOFS1RYTSc5JrGHSUiiJpGrD6aA1m',
                'created_at' => '2024-02-07 16:26:36',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            78 =>
            array (
                'id' => 293,
                'name' => 'Alejo Osorio Jatziri Yamile',
                'email' => 'jalejo@gptservices.com',
                'phone' => 'NA',
                'depto' => 'QHSE',
                'puesto' => 'Trainee de HSE',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'vX4OZXzDsiAptW125DKIVFeg4bmsTgkB2jQdOkaPdZ6WqYmb9Tsk9SzP84V9',
                'created_at' => '2024-02-18 14:02:25',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            79 =>
            array (
                'id' => 296,
                'name' => 'Chávez Huerta Paola',
                'email' => 'pchavez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'recursos Humanos',
                'puesto' => 'Recursos Humanos Jr',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'osat80tfNUeKg4lQQR4nGT9Zsi3wxiqbskYvfF9ViIYIyrGJsy0Ku2HTta4p',
                'created_at' => '2024-03-21 14:45:46',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            80 =>
            array (
                'id' => 298,
                'name' => 'González Cisneros Ingrid Danae',
                'email' => 'igonzalez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'compras',
                'puesto' => 'Comprador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'I9lqEP1NYRUhdrrwJlLtCMK9vUsSCXYXT7lTCtvkaBoMrevMtSITBIxBbMqQ',
                'created_at' => '2024-04-14 12:56:12',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            81 =>
            array (
                'id' => 299,
                'name' => 'Gómez Matilde Christian Alberto',
                'email' => 'NA',
                'phone' => 'NA',
                'depto' => 'Soldadura',
                'puesto' => 'Técnico Soldador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-04-22 17:32:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            82 =>
            array (
                'id' => 301,
                'name' => 'Vazquez Hernández Pablo Angel',
                'email' => 'pvazquez@gptservices.com',
                'phone' => 'NA',
                'depto' => 'QHSE',
            'puesto' => 'Trainee de Sistema de Gestión Integral (SGI)',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '0smgJfG9P4eQrYaEh88dxUhq48xG2XgyD01hnWEKpUVYkWoTRRmOG8QlbjYo',
                'created_at' => '2024-02-07 14:12:27',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            83 =>
            array (
                'id' => 302,
                'name' => 'Padilla Gónzalez Monica Esthela',
                'email' => 'mpadilla@gptservices.com',
                'phone' => '',
                'depto' => 'recursos Humanos',
                'puesto' => 'Trainee de Recursos Humanos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'FGPCAdEhqY8OwC12qKuG7SxY3H1KZJq3BIa5qhpyXFaiEVsVZGtQBivDfC9y',
                'created_at' => '2024-05-22 23:19:57',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            84 =>
            array (
                'id' => 303,
                'name' => 'Sánchez González Luis Adrián',
                'email' => 'lsanchez@gptservices.com',
                'phone' => '',
                'depto' => 'Contratos',
                'puesto' => 'Ingeniero de Contratos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '10C66vnyl8dd4yzt3hrVfK6W4jLAS7yw94H3151lpy8RqgVxNL2Ff8MzinVk',
                'created_at' => '2024-07-08 06:51:38',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            85 =>
            array (
                'id' => 304,
                'name' => 'Contreras García Francisco Alejandro',
                'email' => 'fcontreras@gptservices.com',
                'phone' => '',
                'depto' => 'Contratos',
                'puesto' => 'Ingeniero de Contratos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'LI4vgnPQdoVEIaEVmOxmcAbPpSKlTnW3pPcGCsqQA0xX8yaZQ5bcRkKUaSvI',
                'created_at' => '2024-07-08 06:42:37',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            86 =>
            array (
                'id' => 305,
                'name' => 'Quintanar Pérez María de los Ángeles',
                'email' => 'mquintanar@gptservices.com',
                'phone' => '',
                'depto' => 'Compras',
                'puesto' => 'Comprador',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'aUqFZgtqX5ilYo88od4GWNjDJH6gELucfrukZhrXjTVO0vkiMedt6iP7DZ0B',
                'created_at' => '2024-07-26 05:24:53',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            87 =>
            array (
                'id' => 306,
                'name' => 'Cruz Montes Bruno',
                'email' => 'bcruz@gptservices.com',
                'phone' => '',
                'depto' => 'Administración',
                'puesto' => 'Analista de administración y presupuestos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-07-26 06:42:31',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            88 =>
            array (
                'id' => 307,
                'name' => 'Luna García Francisco',
                'email' => 'fluna@gptservices.com',
                'phone' => '',
                'depto' => 'Almacén',
                'puesto' => 'Almacenista',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-08-19 07:59:18',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            89 =>
            array (
                'id' => 309,
                'name' => 'Butrón González Fernando',
                'email' => 'fbutron@gptservices.com',
                'phone' => '',
                'depto' => 'Calidad',
                'puesto' => 'Inspector de control de calidad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-09-02 01:31:20',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            90 =>
            array (
                'id' => 310,
                'name' => 'Iriarte Pérez Daniel',
                'email' => 'diriarte@gptservices.com',
                'phone' => '',
                'depto' => 'Contratos',
                'puesto' => 'Ingeniero de Contratos',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => 'FdXGW1xrFirUwUSBN6czcPKjy3M4v91PHiGFVjWbRfxEwf2N4jrs9d2RnAMm',
                'created_at' => '2024-09-09 04:48:38',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            91 =>
            array (
                'id' => 311,
                'name' => 'Guerrero Cruz Miguel Ángel',
                'email' => 'vigilanciagpt@gptservices.com',
                'phone' => '',
                'depto' => 'Seguridad Patrimonial',
                'puesto' => 'Guardia de seguridad',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '40i2xJ7jkqStrlygtMFoYF6aVP5XjxgTCWljQweGuEoGqjorKHNqyjTOTqSd',
                'created_at' => '2024-10-02 02:46:56',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            92 =>
            array (
                'id' => 315,
                'name' => 'Alonso Pérez Carlos',
                'email' => 'calonso@gptservices.com',
            'phone' => '(+1) 832 270 8700',
                'depto' => 'Dirección General',
                'puesto' => 'Dirección General',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            93 =>
            array (
                'id' => 331,
                'name' => 'Rodríguez Lara José Carmen',
                'email' => 'jrlara@gptservices.com',
            'phone' => '(+52) 81 8473 8500',
                'depto' => 'Servicios Generales',
                'puesto' => 'Gerencia de Compras y Servicios Generales',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => '',
                'created_at' => '2022-08-06 08:33:32',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
            94 =>
            array (
                'id' => 666,
                'name' => 'Zamudio Juárez Juan Antonio',
                'email' => NULL,
                'phone' => '',
                'depto' => '',
                'puesto' => '',
                'active' => 1,
                'email_verified_at' => NULL,
                'password' => '',
                'remember_token' => NULL,
                'created_at' => '2024-06-04 19:52:04',
                'updated_at' => '2024-10-17 18:30:11',
                'management_id' =>null,
            ),
        ));


    }
}
